### PR TITLE
Add overblog/dataloader-php 0.6

### PR DESCRIPTION
**Pull request by DmytryHo**
Can we add new version of overblog/dataloader-php to this bundle?

### CODE REVIEW

**Review by mcg-web — APPROVED** [review]

**Comment by mcg-web** [comment]
Thank you @DmytryHo !

**Comment by edefimov** [comment]
@mcg-web , could you release a tag for this PR?

**Comment by mcg-web** [comment]
done in v0.5.1 @edefimov .

**Comment by edefimov** [comment]
Thanks!

**Pull request merged**
